<?php

use Illuminate\Database\Seeder;

class InventoryTransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('inventory_transactions')->delete();
        
        \DB::table('inventory_transactions')->insert(array (
            0 => 
            array (
                'id' => 35,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:02:28',
                'transaction_modified_date' => '2006-03-22 16:02:28',
                'product_id' => 80,
                'quantity' => 75,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            1 => 
            array (
                'id' => 36,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:02:48',
                'transaction_modified_date' => '2006-03-22 16:02:48',
                'product_id' => 72,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            2 => 
            array (
                'id' => 37,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:04',
                'transaction_modified_date' => '2006-03-22 16:03:04',
                'product_id' => 52,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            3 => 
            array (
                'id' => 38,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:09',
                'transaction_modified_date' => '2006-03-22 16:03:09',
                'product_id' => 56,
                'quantity' => 120,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            4 => 
            array (
                'id' => 39,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:14',
                'transaction_modified_date' => '2006-03-22 16:03:14',
                'product_id' => 57,
                'quantity' => 80,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            5 => 
            array (
                'id' => 40,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:40',
                'transaction_modified_date' => '2006-03-22 16:03:40',
                'product_id' => 6,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            6 => 
            array (
                'id' => 41,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:47',
                'transaction_modified_date' => '2006-03-22 16:03:47',
                'product_id' => 7,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            7 => 
            array (
                'id' => 42,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:54',
                'transaction_modified_date' => '2006-03-22 16:03:54',
                'product_id' => 8,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            8 => 
            array (
                'id' => 43,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:02',
                'transaction_modified_date' => '2006-03-22 16:04:02',
                'product_id' => 14,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            9 => 
            array (
                'id' => 44,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:07',
                'transaction_modified_date' => '2006-03-22 16:04:07',
                'product_id' => 17,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            10 => 
            array (
                'id' => 45,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:12',
                'transaction_modified_date' => '2006-03-22 16:04:12',
                'product_id' => 19,
                'quantity' => 20,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            11 => 
            array (
                'id' => 46,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:17',
                'transaction_modified_date' => '2006-03-22 16:04:17',
                'product_id' => 20,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            12 => 
            array (
                'id' => 47,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:20',
                'transaction_modified_date' => '2006-03-22 16:04:20',
                'product_id' => 21,
                'quantity' => 20,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            13 => 
            array (
                'id' => 48,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:24',
                'transaction_modified_date' => '2006-03-22 16:04:24',
                'product_id' => 40,
                'quantity' => 120,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            14 => 
            array (
                'id' => 49,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:28',
                'transaction_modified_date' => '2006-03-22 16:04:28',
                'product_id' => 41,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            15 => 
            array (
                'id' => 50,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:31',
                'transaction_modified_date' => '2006-03-22 16:04:31',
                'product_id' => 48,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            16 => 
            array (
                'id' => 51,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:38',
                'transaction_modified_date' => '2006-03-22 16:04:38',
                'product_id' => 51,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            17 => 
            array (
                'id' => 52,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:41',
                'transaction_modified_date' => '2006-03-22 16:04:41',
                'product_id' => 74,
                'quantity' => 20,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            18 => 
            array (
                'id' => 53,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:45',
                'transaction_modified_date' => '2006-03-22 16:04:45',
                'product_id' => 77,
                'quantity' => 60,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            19 => 
            array (
                'id' => 54,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:07',
                'transaction_modified_date' => '2006-03-22 16:05:07',
                'product_id' => 3,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            20 => 
            array (
                'id' => 55,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:11',
                'transaction_modified_date' => '2006-03-22 16:05:11',
                'product_id' => 4,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            21 => 
            array (
                'id' => 56,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:14',
                'transaction_modified_date' => '2006-03-22 16:05:14',
                'product_id' => 5,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            22 => 
            array (
                'id' => 57,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:26',
                'transaction_modified_date' => '2006-03-22 16:05:26',
                'product_id' => 65,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            23 => 
            array (
                'id' => 58,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:32',
                'transaction_modified_date' => '2006-03-22 16:05:32',
                'product_id' => 66,
                'quantity' => 80,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            24 => 
            array (
                'id' => 59,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:47',
                'transaction_modified_date' => '2006-03-22 16:05:47',
                'product_id' => 1,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            25 => 
            array (
                'id' => 60,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:51',
                'transaction_modified_date' => '2006-03-22 16:05:51',
                'product_id' => 34,
                'quantity' => 60,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            26 => 
            array (
                'id' => 61,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:06:00',
                'transaction_modified_date' => '2006-03-22 16:06:00',
                'product_id' => 43,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            27 => 
            array (
                'id' => 62,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:06:03',
                'transaction_modified_date' => '2006-03-22 16:06:03',
                'product_id' => 81,
                'quantity' => 125,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            28 => 
            array (
                'id' => 63,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:07:56',
                'transaction_modified_date' => '2006-03-24 11:03:00',
                'product_id' => 80,
                'quantity' => 30,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            29 => 
            array (
                'id' => 64,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:08:19',
                'transaction_modified_date' => '2006-03-22 16:08:59',
                'product_id' => 7,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            30 => 
            array (
                'id' => 65,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:08:29',
                'transaction_modified_date' => '2006-03-22 16:08:59',
                'product_id' => 51,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            31 => 
            array (
                'id' => 66,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:08:37',
                'transaction_modified_date' => '2006-03-22 16:08:59',
                'product_id' => 80,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            32 => 
            array (
                'id' => 67,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:09:46',
                'transaction_modified_date' => '2006-03-22 16:10:27',
                'product_id' => 1,
                'quantity' => 15,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            33 => 
            array (
                'id' => 68,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:10:06',
                'transaction_modified_date' => '2006-03-22 16:10:27',
                'product_id' => 43,
                'quantity' => 20,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            34 => 
            array (
                'id' => 69,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:11:39',
                'transaction_modified_date' => '2006-03-24 11:00:55',
                'product_id' => 19,
                'quantity' => 20,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            35 => 
            array (
                'id' => 70,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:11:56',
                'transaction_modified_date' => '2006-03-24 10:59:41',
                'product_id' => 48,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            36 => 
            array (
                'id' => 71,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:12:29',
                'transaction_modified_date' => '2006-03-24 10:57:38',
                'product_id' => 8,
                'quantity' => 17,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            37 => 
            array (
                'id' => 72,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:41:30',
                'transaction_modified_date' => '2006-03-24 10:41:30',
                'product_id' => 81,
                'quantity' => 200,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            38 => 
            array (
                'id' => 73,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:41:33',
                'transaction_modified_date' => '2006-03-24 10:41:42',
                'product_id' => 81,
                'quantity' => 200,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #40',
            ),
            39 => 
            array (
                'id' => 74,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:53:13',
                'transaction_modified_date' => '2006-03-24 10:53:13',
                'product_id' => 48,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            40 => 
            array (
                'id' => 75,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:53:16',
                'transaction_modified_date' => '2006-03-24 10:55:46',
                'product_id' => 48,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #39',
            ),
            41 => 
            array (
                'id' => 76,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:53:36',
                'transaction_modified_date' => '2006-03-24 10:53:36',
                'product_id' => 43,
                'quantity' => 300,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            42 => 
            array (
                'id' => 77,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:53:39',
                'transaction_modified_date' => '2006-03-24 10:56:57',
                'product_id' => 43,
                'quantity' => 300,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #38',
            ),
            43 => 
            array (
                'id' => 78,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:54:04',
                'transaction_modified_date' => '2006-03-24 10:54:04',
                'product_id' => 41,
                'quantity' => 200,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            44 => 
            array (
                'id' => 79,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:54:07',
                'transaction_modified_date' => '2006-03-24 10:58:40',
                'product_id' => 41,
                'quantity' => 200,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #36',
            ),
            45 => 
            array (
                'id' => 80,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:54:33',
                'transaction_modified_date' => '2006-03-24 10:54:33',
                'product_id' => 19,
                'quantity' => 30,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            46 => 
            array (
                'id' => 81,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:54:35',
                'transaction_modified_date' => '2006-03-24 11:02:02',
                'product_id' => 19,
                'quantity' => 30,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #33',
            ),
            47 => 
            array (
                'id' => 82,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:54:58',
                'transaction_modified_date' => '2006-03-24 10:54:58',
                'product_id' => 34,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            48 => 
            array (
                'id' => 83,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:55:02',
                'transaction_modified_date' => '2006-03-24 11:03:00',
                'product_id' => 34,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #30',
            ),
            49 => 
            array (
                'id' => 84,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:48:15',
                'transaction_modified_date' => '2006-04-04 11:41:14',
                'product_id' => 6,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            50 => 
            array (
                'id' => 85,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:48:23',
                'transaction_modified_date' => '2006-04-04 11:41:14',
                'product_id' => 4,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            51 => 
            array (
                'id' => 86,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-24 14:49:16',
                'transaction_modified_date' => '2006-03-24 14:49:16',
                'product_id' => 80,
                'quantity' => 20,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            52 => 
            array (
                'id' => 87,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-24 14:49:20',
                'transaction_modified_date' => '2006-03-24 14:49:20',
                'product_id' => 81,
                'quantity' => 50,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            53 => 
            array (
                'id' => 88,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-24 14:50:09',
                'transaction_modified_date' => '2006-03-24 14:50:09',
                'product_id' => 1,
                'quantity' => 25,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            54 => 
            array (
                'id' => 89,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-24 14:50:14',
                'transaction_modified_date' => '2006-03-24 14:50:14',
                'product_id' => 43,
                'quantity' => 25,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            55 => 
            array (
                'id' => 90,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-24 14:50:18',
                'transaction_modified_date' => '2006-03-24 14:50:18',
                'product_id' => 81,
                'quantity' => 25,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            56 => 
            array (
                'id' => 91,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:51:03',
                'transaction_modified_date' => '2006-04-04 11:09:24',
                'product_id' => 40,
                'quantity' => 50,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            57 => 
            array (
                'id' => 92,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:55:03',
                'transaction_modified_date' => '2006-04-04 11:06:56',
                'product_id' => 21,
                'quantity' => 20,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            58 => 
            array (
                'id' => 93,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:55:39',
                'transaction_modified_date' => '2006-04-04 11:06:13',
                'product_id' => 5,
                'quantity' => 25,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            59 => 
            array (
                'id' => 94,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:55:52',
                'transaction_modified_date' => '2006-04-04 11:06:13',
                'product_id' => 41,
                'quantity' => 30,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            60 => 
            array (
                'id' => 95,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:56:09',
                'transaction_modified_date' => '2006-04-04 11:06:13',
                'product_id' => 40,
                'quantity' => 30,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            61 => 
            array (
                'id' => 96,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-30 16:46:34',
                'transaction_modified_date' => '2006-03-30 16:46:34',
                'product_id' => 34,
                'quantity' => 12,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            62 => 
            array (
                'id' => 97,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-30 17:23:27',
                'transaction_modified_date' => '2006-03-30 17:23:27',
                'product_id' => 34,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            63 => 
            array (
                'id' => 98,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-30 17:24:33',
                'transaction_modified_date' => '2006-03-30 17:24:33',
                'product_id' => 34,
                'quantity' => 1,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            64 => 
            array (
                'id' => 99,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-03 13:50:08',
                'transaction_modified_date' => '2006-04-03 13:50:15',
                'product_id' => 48,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            65 => 
            array (
                'id' => 100,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:00:54',
                'transaction_modified_date' => '2006-04-04 11:00:54',
                'product_id' => 57,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            66 => 
            array (
                'id' => 101,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:00:56',
                'transaction_modified_date' => '2006-04-04 11:08:49',
                'product_id' => 57,
                'quantity' => 100,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #46',
            ),
            67 => 
            array (
                'id' => 102,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:01:14',
                'transaction_modified_date' => '2006-04-04 11:01:14',
                'product_id' => 34,
                'quantity' => 50,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            68 => 
            array (
                'id' => 103,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:01:35',
                'transaction_modified_date' => '2006-04-04 11:01:35',
                'product_id' => 43,
                'quantity' => 250,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            69 => 
            array (
                'id' => 104,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-04-04 11:01:37',
                'transaction_modified_date' => '2006-04-04 11:01:37',
                'product_id' => 43,
                'quantity' => 300,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #41',
            ),
            70 => 
            array (
                'id' => 105,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:01:55',
                'transaction_modified_date' => '2006-04-04 11:01:55',
                'product_id' => 8,
                'quantity' => 25,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            71 => 
            array (
                'id' => 106,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:01:58',
                'transaction_modified_date' => '2006-04-04 11:07:37',
                'product_id' => 8,
                'quantity' => 25,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #48',
            ),
            72 => 
            array (
                'id' => 107,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:02:17',
                'transaction_modified_date' => '2006-04-04 11:02:17',
                'product_id' => 34,
                'quantity' => 300,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            73 => 
            array (
                'id' => 108,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:02:19',
                'transaction_modified_date' => '2006-04-04 11:08:14',
                'product_id' => 34,
                'quantity' => 300,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #47',
            ),
            74 => 
            array (
                'id' => 109,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:02:37',
                'transaction_modified_date' => '2006-04-04 11:02:37',
                'product_id' => 19,
                'quantity' => 25,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            75 => 
            array (
                'id' => 110,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:02:39',
                'transaction_modified_date' => '2006-04-04 11:41:14',
                'product_id' => 19,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #42',
            ),
            76 => 
            array (
                'id' => 111,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:02:56',
                'transaction_modified_date' => '2006-04-04 11:02:56',
                'product_id' => 19,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            77 => 
            array (
                'id' => 112,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:02:58',
                'transaction_modified_date' => '2006-04-04 11:07:37',
                'product_id' => 19,
                'quantity' => 25,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #48',
            ),
            78 => 
            array (
                'id' => 113,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:03:12',
                'transaction_modified_date' => '2006-04-04 11:03:12',
                'product_id' => 72,
                'quantity' => 50,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            79 => 
            array (
                'id' => 114,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:03:14',
                'transaction_modified_date' => '2006-04-04 11:08:49',
                'product_id' => 72,
                'quantity' => 50,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #46',
            ),
            80 => 
            array (
                'id' => 115,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:03:38',
                'transaction_modified_date' => '2006-04-04 11:03:38',
                'product_id' => 41,
                'quantity' => 50,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            81 => 
            array (
                'id' => 116,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:03:39',
                'transaction_modified_date' => '2006-04-04 11:09:24',
                'product_id' => 41,
                'quantity' => 50,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => 'Fill Back Ordered product, Order #45',
            ),
            82 => 
            array (
                'id' => 117,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:04:55',
                'transaction_modified_date' => '2006-04-04 11:05:04',
                'product_id' => 34,
                'quantity' => 87,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            83 => 
            array (
                'id' => 118,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:35:50',
                'transaction_modified_date' => '2006-04-04 11:35:54',
                'product_id' => 51,
                'quantity' => 30,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            84 => 
            array (
                'id' => 119,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:35:51',
                'transaction_modified_date' => '2006-04-04 11:35:54',
                'product_id' => 7,
                'quantity' => 30,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            85 => 
            array (
                'id' => 120,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:36:15',
                'transaction_modified_date' => '2006-04-04 11:36:21',
                'product_id' => 17,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            86 => 
            array (
                'id' => 121,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:36:39',
                'transaction_modified_date' => '2006-04-04 11:36:47',
                'product_id' => 6,
                'quantity' => 90,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            87 => 
            array (
                'id' => 122,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:37:06',
                'transaction_modified_date' => '2006-04-04 11:37:09',
                'product_id' => 4,
                'quantity' => 30,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            88 => 
            array (
                'id' => 123,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:37:45',
                'transaction_modified_date' => '2006-04-04 11:37:49',
                'product_id' => 48,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            89 => 
            array (
                'id' => 124,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:38:07',
                'transaction_modified_date' => '2006-04-04 11:38:11',
                'product_id' => 48,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            90 => 
            array (
                'id' => 125,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:38:27',
                'transaction_modified_date' => '2006-04-04 11:38:32',
                'product_id' => 41,
                'quantity' => 10,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            91 => 
            array (
                'id' => 126,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:38:48',
                'transaction_modified_date' => '2006-04-04 11:38:53',
                'product_id' => 43,
                'quantity' => 5,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            92 => 
            array (
                'id' => 127,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:39:12',
                'transaction_modified_date' => '2006-04-04 11:39:29',
                'product_id' => 40,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            93 => 
            array (
                'id' => 128,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:39:50',
                'transaction_modified_date' => '2006-04-04 11:39:53',
                'product_id' => 8,
                'quantity' => 20,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            94 => 
            array (
                'id' => 129,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:40:13',
                'transaction_modified_date' => '2006-04-04 11:40:16',
                'product_id' => 80,
                'quantity' => 15,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            95 => 
            array (
                'id' => 130,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:40:32',
                'transaction_modified_date' => '2006-04-04 11:40:38',
                'product_id' => 74,
                'quantity' => 20,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            96 => 
            array (
                'id' => 131,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:41:39',
                'transaction_modified_date' => '2006-04-04 11:41:45',
                'product_id' => 72,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            97 => 
            array (
                'id' => 132,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:42:17',
                'transaction_modified_date' => '2006-04-04 11:42:26',
                'product_id' => 3,
                'quantity' => 50,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            98 => 
            array (
                'id' => 133,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:42:24',
                'transaction_modified_date' => '2006-04-04 11:42:26',
                'product_id' => 8,
                'quantity' => 3,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            99 => 
            array (
                'id' => 134,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:42:48',
                'transaction_modified_date' => '2006-04-04 11:43:08',
                'product_id' => 20,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            100 => 
            array (
                'id' => 135,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:43:05',
                'transaction_modified_date' => '2006-04-04 11:43:08',
                'product_id' => 52,
                'quantity' => 40,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
            101 => 
            array (
                'id' => 136,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-04-25 17:04:05',
                'transaction_modified_date' => '2006-04-25 17:04:57',
                'product_id' => 56,
                'quantity' => 110,
                'purchase_order_id' => NULL,
                'customer_order_id' => NULL,
                'comments' => NULL,
            ),
        ));
        
        
    }
}
